apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-0b1d88e3b0a74e2795aa182003cc9de5-depl
  labels:
    app: coll-0b1d88e3b0a74e2795aa182003cc9de5
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-0b1d88e3b0a74e2795aa182003cc9de5
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-0b1d88e3b0a74e2795aa182003cc9de5
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-0b1d88e3b0a74e2795aa182003cc9de5
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-0b1d88e3b0a74e2795aa182003cc9de5
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping